### ISSUE TITLE
Create classroom as a pop up

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-classroom#10]
## Current Behavior

Users have to navigate to <MFE_HOST>/classroom/create to create a new classroom. They can do it from the manage page. The navigation is unnecessary and if the user wants to cancel the process they then have to be redirected back to the manage page.

## Possible Solution

The "New Classroom" button should trigger a pop up where the user can finish the classroom creation process or cancel the process which closes the pop up window.

**Comment by Salik-Rafiq** [comment]
Removed the /create/ path - the create classroom is now in a popup on the manage page.
