### ISSUE TITLE
Window size seems to not fit horizontally

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-classroom#11]
## Current Behavior

There is a scrolling back along the horizontal axis. The view should fit the dimension of the browser.

![image](https://user-images.githubusercontent.com/13796098/140409504-92049ddd-5824-4f24-a3ee-35b84a072b79.png)
![image](https://user-images.githubusercontent.com/13796098/140409903-09e1173c-e3cf-4d70-aee4-5cdcdb02c496.png)

## Possible Solution

Not sure what causes this.

## Steps to Reproduce (for bugs)

1. Create a new classroom

## Your Environment

* Version used:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Salik-Rafiq** [comment]
Looks like the NavBar CSS was adding in negative margins. Tidied that up and removed some necessary CSS as well.
