### ISSUE TITLE
When adding a course, unselected courses display the same behaviour as the selected courses

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-classroom#14]
## Expected Behavior

Only the button for the selected course should have a spinner animation. The other buttons should be disabled, as they are currently, but they shouldn't have a loading spinner.

## Current Behavior

The buttons of all courses available are disabled and show a spinner.

![image](https://user-images.githubusercontent.com/13796098/140411409-1ea5fce9-3dc4-40cc-b335-6013c56c02d0.png)

**Comment by Salik-Rafiq** [comment]
Updated it so that the spinner is only on the course being added.
