### ISSUE TITLE
Add a basic classroom dashboard

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-classroom#2]
Currently accessing a given classroom requires the enterprise slug to be in the URL and the user needs to have the classroom UUID. 

Until we have a fully fledge teacher dashboard, we need a very basic page displaying all the classrooms created by the user.

**Comment by BbrSofiane** [comment]
Can we add a "New classroom" button on the manage page? Right now the only path to creating a new classroom is to navigate to the URL. 

Can we also make clicking the button open a pop up of the new classroom form?

**Comment by Salik-Rafiq** [comment]
Odd. The New Classroom button should be there.  It doesn't appear if the user is an Admin. I will have a look.

Can you make the popup a ticket?

**Comment by Salik-Rafiq** [comment]
The Add Classroom button should be OK now. have added additional checks for the _admin role. So it should appear when that role is in the roles array.
