### ISSUE TITLE
Use fetchAuthenticatedUser to get the enterprise UUID

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-classroom#9]
## Current Behavior

Creating a classroom requires an enterprise (school) UUID, the current implementation uses the enterprise slug provided in the URL to fetch the enterprise UUID.

## Possible Solution

Use [fetchAuthenticatedUser](https://edx.github.io/frontend-platform/module-Auth.html) and the decoded JWT token to get the enterprise UUID associated with the `enterprise_admin` role. 

```
import { fetchAuthenticatedUser,} from '@edx/frontend-platform/auth';

const authenticatedUser = await fetchAuthenticatedUser(); // validates and decodes JWT token
```

That way we keep implementation details away from the way we construct our URL routing in case the implementation changes  (e.g. the enterprise UUID is no longer required).

**Comment by Salik-Rafiq** [comment]
This has been done. I'll just close it.
